apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template: # Configuration of Pod has its own "metadata" and "spec" section
    metadata:
      labels:
        app: mongo
    spec:
      containers: # Which image? Which Port?
      - name: mongodb # any name
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: # Select pods to forward the requests
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 # maps with containerPort: 27017
